name: Deploy STG Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "Staging"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Deploy Vercel
        uses: ./.github/actions/deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          mode: production
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
