name: Pull Request

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Tests
        run: npm run test:ci

      - name: Build
        run: npm run build
